# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_picture_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='profile',
        ),
    ]
